- arithmetic operators
    - addition + and .add()
    - subtraction - and .subtract()
    - multiplication * and .multiply()
    - division / and .divide()
    - integer division // and .floor_divide()
    - exponentiation ** and .power()
    - cgd lcm
    - log log2 log10 
    - sin cos tan
    
DONE ^
    
- floating functions
    - isnan
    - ceil / floor

- math / stat operators
    - mean
    - std / var
    - sqrt cbrt


---
title: "Math COME BACK"
description: "Many basic mathematical and statistical functions are available for ndarrays. Those covered in this brick include the mean, min, max, sum, product, standard deviation, and variance functions."
tags: Numpy, Mathematics: Basics
URL: https://github.com/ageron/handson-ml
Licence: Apache License 2.0
Creator: 
Meta: "mean max sum prod std var"

---

# Key Code&

In [2]:
import numpy as np

In [ ]:
# These methods apply to all elements regardless of the array shape
ndarray.mean()
ndarray.min()
ndarray.max()
ndarray.sum()
ndarray.prod() # Note: *NOT* matrix multiplication
ndarray.std()
ndarray.var()

All these functions accept an optional argument `axis` which lets you perform the operation on elements along the given axis.

In [ ]:
# axis = 0  => sum across matricies
# axis = 1  => sum across rows
# axis = 2  => sum across columns

# Example&

In [52]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print(a)
print("mean =", a.mean())

[[ -2.5   3.1   7. ]
 [ 10.   11.   12. ]]
mean = 6.76666666667


In [53]:
for func in (a.min, a.max, a.sum, a.prod, a.std, a.var):
    print(func.__name__, "=", func())

min = -2.5
max = 12.0
sum = 40.6
prod = -71610.0
std = 5.08483584352
var = 25.8555555556


# Example&

In [54]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [55]:
c.sum(axis=0)  # sum across matrices

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [56]:
c.sum(axis=1)  # sum across rows

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

You can also sum over multiple axes:

In [57]:
c.sum(axis=(0,2))  # sum across matrices and columns

array([ 60,  92, 124])

In [58]:
0+1+2+3 + 12+13+14+15, 4+5+6+7 + 16+17+18+19, 8+9+10+11 + 20+21+22+23

(60, 92, 124)

descriptio "NumPy also provides fast elementwise functions called universal functions, or ufuncs. They are vectorized wrappers of simple functions. For example square returns a new ndarray which is a copy of the original ndarray except that each element is squared. These functions are abs, sqrt, exp, log, sign, ceil, modf, isnan, and cos."

# Key Code&

In [2]:
import numpy as np

In [ ]:
# These methods apply to all elements regardless of the array shape
np.abs(ndarray)
np.ceil(ndarray)
np.cos(ndarray)
np.exp(ndarray)
np.isnan(ndarray)
np.log(ndarray)
np.modf(ndarray)
np.sqrt(ndarray)
np.sqrt(ndarray)
np.sqrt(ndarray)

# Example&

In [59]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
np.square(a)

array([[   6.25,    9.61,   49.  ],
       [ 100.  ,  121.  ,  144.  ]])

In [60]:
print("Original ndarray")
print(a)
for func in (np.abs, np.sqrt, np.exp, np.log, np.sign, np.ceil, np.modf, np.isnan, np.cos):
    print("\n", func.__name__)
    print(func(a))

Original ndarray
[[ -2.5   3.1   7. ]
 [ 10.   11.   12. ]]

 absolute
[[  2.5   3.1   7. ]
 [ 10.   11.   12. ]]

 sqrt
[[        nan  1.76068169  2.64575131]
 [ 3.16227766  3.31662479  3.46410162]]

 exp
[[  8.20849986e-02   2.21979513e+01   1.09663316e+03]
 [  2.20264658e+04   5.98741417e+04   1.62754791e+05]]

 log
[[        nan  1.13140211  1.94591015]
 [ 2.30258509  2.39789527  2.48490665]]

 sign
[[-1.  1.  1.]
 [ 1.  1.  1.]]

 ceil
[[ -2.   4.   7.]
 [ 10.  11.  12.]]

 modf
(array([[-0.5,  0.1,  0. ],
       [ 0. ,  0. ,  0. ]]), array([[ -2.,   3.,   7.],
       [ 10.,  11.,  12.]]))

 isnan
[[False False False]
 [False False False]]

 cos
[[-0.80114362 -0.99913515  0.75390225]
 [-0.83907153  0.0044257   0.84385396]]


-c:5: RuntimeWarning: invalid value encountered in sqrt
-c:5: RuntimeWarning: invalid value encountered in log


# Learn More&

## Binary ufuncs
There are also many binary ufuncs, that apply elementwise on two `ndarray`s.  Broadcasting rules are applied if the arrays do not have the same shape:

In [61]:
a = np.array([1, -2, 3, 4])
b = np.array([2, 8, -1, 7])
np.add(a, b)  # equivalent to a + b

array([ 3,  6,  2, 11])

In [62]:
np.greater(a, b)  # equivalent to a > b

array([False, False,  True, False], dtype=bool)

In [63]:
np.maximum(a, b)

array([2, 8, 3, 7])

In [64]:
np.copysign(a, b)

array([ 1.,  2., -3.,  4.])