---
title: "Boolean Arrays As Masks"
description: "Using boolean arrays as masks is a way to select subsets of an array that pass some boolean expression. To select a subset of particular values, simply index the boolean expression to get back a 1D array of the values."
tags: Numpy
URL: https://github.com/jakevdp/PythonDataScienceHandbook/
Licence: MIT for code, Text is copyrighted
Creator: 
Meta: "select true from boolean"

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Boolean Arrays As Masks
        </h1>
        <p>Using boolean arrays as masks is a way to select subsets of an array that pass some boolean expression. To select a subset of particular values, simply index the boolean expression to get back a 1D array of the values.</p>
    	</div>
		</div> 

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>
			

In [30]:
import numpy as np

In [38]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [41]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [42]:
x[x < 5]

array([0, 3, 3, 3, 2, 4])