---
title: "Center An Array"
description: "Centering an array is a common example of NumPy's broadcasting rules being used in practice. "
tags: Numpy
URL: https://github.com/jakevdp/PythonDataScienceHandbook/
Licence: MIT for code, Text is copyrighted
Creator: 
Meta: "broadcasting rules broadcast"

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Center An Array
        </h1>
        <p>Centering an array is a common example of NumPy's broadcasting rules being used in practice. </p>
    	</div>
		</div> 

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>
			

In [21]:
X = np.random.random((10, 3))
X

array([[0.02775005, 0.9897241 , 0.46408945],
       [0.8880543 , 0.36712553, 0.95054051],
       [0.91220255, 0.04173485, 0.47134025],
       [0.11850064, 0.52716986, 0.18893768],
       [0.71431642, 0.73992235, 0.15228109],
       [0.62768072, 0.60951088, 0.84766633],
       [0.52438398, 0.73774477, 0.41366023],
       [0.14723927, 0.51002467, 0.53989432],
       [0.64255513, 0.43264807, 0.18674427],
       [0.1217504 , 0.49295823, 0.94881267]])

In [22]:
Xmean = X.mean(0)
Xmean

array([0.47244335, 0.54485633, 0.51639668])

In [24]:
# this is the broadcasting step:
X_centered = X - Xmean

In [25]:
# check that mean is basically 0
X_centered.mean(0)

array([-2.22044605e-17, -1.11022302e-17, -6.66133815e-17])