---
title: "Combined Indexing"
description: "Fancy indexing is a lot like accessing arrays with slices, boolean masks, or simple indices. However, for fancy indexing we pass in arrays of indices in place of scalars to access multiple elements at one time."
tags: Numpy
URL: https://github.com/jakevdp/PythonDataScienceHandbook/
Licence: MIT for code, Text is copyrighted
Creator: 
Meta: "fancy and simple indexing slices and masking and fancy"

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Combined Indexing
        </h1>
        <p>Fancy indexing is a lot like accessing arrays with slices, boolean masks, or simple indices. However, for fancy indexing we pass in arrays of indices in place of scalars to access multiple elements at one time.</p>
    	</div>
		</div> 

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>
			

In [49]:
import numpy as np

In [51]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
# fancy and simple indexing
X[2, [2, 0, 1]]

array([10,  8,  9])

In [53]:
# fancy indexing and slices 
X[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [55]:
# fancy indexing and masking
row = np.array([0, 1, 2])
mask = np.array([1, 0, 1, 0], dtype=bool)
X[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])