---
title: "Eigenvalues and Eigenvectors"
description: "NumPy's eig function computes the eigenvalues and eigenvectors of a square matrix."
tags: Numpy
URL: https://github.com/ageron/handson-ml
Licence: Apache License 2.0
Creator: 
Meta: ""

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Eigenvalues and Eigenvectors
        </h1>
        <p>NumPy's eig function computes the eigenvalues and eigenvectors of a square matrix.</p>
    	</div>
		</div> 

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Key Code
    	</span>
		</div>
		</div>
			

In [ ]:
import numpy as np
import numpy.linalg as linalg

In [ ]:
# compute λ, v for square matrix m
eigenvalues, eigenvectors = linalg.eig(m)

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>
			

In [23]:
m3 = np.array([[1,2,3],[5,7,11],[21,29,31]])
m3

array([[ 1,  2,  3],
       [ 5,  7, 11],
       [21, 29, 31]])

In [150]:
eigenvalues, eigenvectors = linalg.eig(m3)
eigenvalues # λ

array([ 42.26600592,  -0.35798416,  -2.90802176])

In [151]:
eigenvectors # v

array([[-0.08381182, -0.76283526, -0.18913107],
       [-0.3075286 ,  0.64133975, -0.6853186 ],
       [-0.94784057, -0.08225377,  0.70325518]])

In [152]:
m3.dot(eigenvectors) - eigenvalues * eigenvectors  # m3.v - λ*v = 0

array([[  8.88178420e-15,   2.49800181e-15,  -3.33066907e-16],
       [  1.77635684e-14,  -1.66533454e-16,  -3.55271368e-15],
       [  3.55271368e-14,   3.61516372e-15,  -4.44089210e-16]])

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Learn More
    	</span>
		</div>
		</div>
			

Learn more about the [eigenvalues and eigenvectors](https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors) of a square matrix: