---
title: "Identity Matrix"
description: "The product of a matrix by its inverse returns the identiy matrix (with small floating point errors). Also, a NxN identity matrix can be made with the NumPy's eye method."
tags: Numpy
URL: https://github.com/ageron/handson-ml
Licence: Apache License 2.0
Creator: 
Meta: ""

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Identity Matrix
        </h1>
        <p>The product of a matrix by its inverse returns the identiy matrix (with small floating point errors). Also, a NxN identity matrix can be made with the NumPy's eye method.</p>
    	</div>
		</div> 

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Key Code
    	</span>
		</div>
		</div>
			

In [ ]:
import numpy as np

In [ ]:
# create a NxN identity matrix
np.eye(N)

In [ ]:
# take the dot product of any square matrix and its inverse
import numpy.linalg as linalg
arr.dot(linalg.inv(arr))

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>
			

## Create an array

In [141]:
import numpy.linalg as linalg

arr = np.array([[1,2,3],[5,7,11],[21,29,31]])
arr

array([[ 1,  2,  3],
       [ 5,  7, 11],
       [21, 29, 31]])

## Calculate dot product of `arr` and its inverse

In [144]:
arr.dot(linalg.inv(arr))

array([[  1.00000000e+00,  -1.11022302e-16,  -6.93889390e-18],
       [ -1.33226763e-15,   1.00000000e+00,  -5.55111512e-17],
       [  2.88657986e-15,   0.00000000e+00,   1.00000000e+00]])

## Create an identity matrix of size NxN by calling `eye`:

In [145]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])