---
title: "Iterating Over a NumPy Array"
description: "Iterating over a ndarray is very similar to iterating over a regular python array."
tags: Numpy, Iteration
URL: https://github.com/ageron/handson-ml
Licence: Apache License 2.0
Creator: 
Meta: ""

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Iterating Over a NumPy Array
        </h1>
        <p>Iterating over a ndarray is very similar to iterating over a regular python array.</p>
    	</div>
		</div> 

# Key Code

In [2]:
import numpy as np

Iterating is always done with respect to the first axis

In [9]:
arr = np.arange(8).reshape(2, 4)
for a in arr:
    print(a)

[0 1 2 3]
[4 5 6 7]


If you want to iterate on *all* elements in a `ndarray`, simply iterate over the `flat` attribute:

In [10]:
for a in arr.flat:
    print(a)

0
1
2
3
4
5
6
7


 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>
			

In [103]:
# A 3D array (composed of two 3x4 matrices)
c = np.arange(24).reshape(2, 3, 4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [104]:
for m in c:
    print("Item:")
    print(m)

Item:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Item:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [105]:
for i in range(len(c)):  # Note that len(c) == c.shape[0]
    print("Item:")
    print(c[i])

Item:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Item:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
