---
title: "Matrix Diagonals"
description: "Extract a diagonal from a NumPy matrix."
tags: Numpy
URL: https://github.com/ageron/handson-ml
Licence: Apache License 2.0
Creator: 
Meta: ""

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Matrix Diagonals
        </h1>
        <p>Extract a diagonal from a NumPy matrix.</p>
    	</div>
		</div> 

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Key Code
    	</span>
		</div>
		</div>
			

In [ ]:
import numpy as np

In [ ]:
# diagional of matrix m. 
np.diag(m)

There is another optional argument `k` to specify the diagonal of interest. By default, diagonal k = 0. k > 0 is for a diagonal above the main diagonal. k < 0 is for a diagonal below the main diagonal.

In [ ]:
np.diag(m, k = 2)

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>
			

In [24]:
m3 = np.array([[1,2,3],[5,7,11],[21,29,31]])
m3

array([[ 1,  2,  3],
       [ 5,  7, 11],
       [21, 29, 31]])

In [25]:
np.diag(m3)

array([ 1,  7, 31])

In [27]:
np.diag(m3, k = -1)

array([ 5, 29])