---
title: "Modify Values of An Array With Fancy Indexing"
description: "Fancy indexing can be used to modify parts of an existing array."
tags: Numpy
URL: https://github.com/jakevdp/PythonDataScienceHandbook/
Licence: MIT for code, Text is copyrighted
Creator: 
Meta: ""

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Modify Values of An Array With Fancy Indexing
        </h1>
        <p>Fancy indexing can be used to modify parts of an existing array.</p>
    	</div>
		</div> 

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>
			

In [77]:
import numpy as np

In [81]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
x

array([ 0, 99, 99,  3, 99,  5,  6,  7, 99,  9])

In [82]:
x[i] -= 10
x

array([ 0, 89, 89,  3, 89,  5,  6,  7, 89,  9])

**Warning:** repeated indices with these operations can create unexpected results. For example:

In [83]:
x = np.zeros(10)
x[[0, 0]] = [4, 6]
x

array([6., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

This operation first assigns `x[0] = 4` and then `x[0] = 6`. Makes sense but now consider:

In [84]:
i = [2, 3, 3, 4, 4, 4]
x[i] += 1
x

array([6., 0., 1., 1., 1., 0., 0., 0., 0., 0.])

You may expect `x[3] = 2` and `x[4] = 3`. This result occurs because `x[i] + 1. x[i] + 1` is evaluated and then assigned to `x[i]`. The assignment happens multiple times not the incrementation. To get the incremention behavior, use the `at` method:

In [85]:
x = np.zeros(10)
np.add.at(x, i, 1)
x

array([0., 0., 1., 2., 3., 0., 0., 0., 0., 0.])