---
title: "Multi-Dimensional Arrays: Fancy Indexing"
description: "Indexing a multi-dimensional array with fancy indexing. It's just like regular indexing, but you pass a list of indices instead of a scalar value for the index."
tags: Numpy
URL: https://github.com/ageron/handson-ml
Licence: Apache License 2.0
Creator: 
Meta: ""

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Multi-Dimensional Arrays: Fancy Indexing
        </h1>
        <p>Indexing a multi-dimensional array with fancy indexing. It's just like regular indexing, but you pass a list of indices instead of a scalar value for the index.</p>
    	</div>
		</div> 

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Key Code
    	</span>
		</div>
		</div>
			

In [2]:
import numpy as np

In [ ]:
# specify a list of indices that you are interested in
# for rows and/or columns
ndarray[rows, columns]

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>
			

In [80]:
b = np.arange(48).reshape(4, 12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [86]:
# rows 0 and 2, columns 2 to 4 (5-1)
b[(0,2), 2:5]

array([[ 2,  3,  4],
       [26, 27, 28]])

In [87]:
# all rows, columns -1 (last), 2 and -1 (again, and in this order)
b[:, (-1, 2, -1)]

array([[11,  2, 11],
       [23, 14, 23],
       [35, 26, 35],
       [47, 38, 47]])

If you provide multiple index arrays, you get a 1D `ndarray` containing the values of the elements at the specified coordinates.

In [88]:
# returns a 1D array with b[-1, 5], b[2, 9], b[-1, 1] and b[2, 9] (again)
b[(-1, 2, -1, 2), (5, 9, 1, 9)]

array([41, 33, 37, 33])