---
title: "Indexing And Slicing NumPy Arrays"
description: ""
tags: python: basics
URL: https://github.com/chrisalbon/notes
Licence: 
Creator: 
Meta: 

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 75px;text-align: center; padding-top:5px">
        <h1>
      	Indexing And Slicing NumPy Arrays
        </h1>
        <p></p>
    	</div>
		</div> 

In [1]:
# Import modules
import numpy as np

In [2]:
# Create a 2x2 array
battle_deaths = [[344, 2345], [253, 4345]]
deaths = np.array(battle_deaths)
deaths

array([[ 344, 2345],
       [ 253, 4345]])

In [3]:
# Select the top row, second item
deaths[0, 1]

2345

In [4]:
# Select the second column
deaths[:, 1]

array([2345, 4345])

In [5]:
# Select the second row
deaths[1, :]

array([ 253, 4345])

In [6]:
# Create an array of civilian deaths
civilian_deaths = np.array([4352, 233, 3245, 256, 2394])
civilian_deaths

array([4352,  233, 3245,  256, 2394])

In [7]:
# Find the index of battles with less than 500 deaths
few_civ_deaths = np.where(civilian_deaths < 500)
few_civ_deaths

(array([1, 3]),)

In [8]:
# Find the number of civilian deaths in battles with less than 500 deaths
civ_deaths = civilian_deaths[few_civ_deaths]
civ_deaths

array([233, 256])