---
title: "Partial Sorting: Partitioning"
description: "NumPy's np.partition function allows us to find the smallest k values in an array. The partition function takes a pivot and an array and returns a new array the values smaller than the pivot to the left of the partition and the values larger than the pivot to the right (with no particular order on either side of the pivot)."
tags: Numpy
URL: https://github.com/jakevdp/PythonDataScienceHandbook/
Licence: MIT for code, Text is copyrighted
Creator: 
Meta: "np.partition multidimensional partition"

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Partial Sorting: Partitioning
        </h1>
        <p>NumPy's np.partition function allows us to find the smallest k values in an array. The partition function takes a pivot and an array and returns a new array the values smaller than the pivot to the left of the partition and the values larger than the pivot to the right (with no particular order on either side of the pivot).</p>
    	</div>
		</div> 

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Key Code
    	</span>
		</div>
		</div>
			

In [88]:
import numpy as np

## Create arrays

In [101]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
x

array([7, 2, 3, 1, 6, 5, 4])

In [102]:
rand = np.random.RandomState(42)
M = rand.randint(0, 10, (4, 6))
print(M)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


## Partition

In [99]:
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [103]:
np.partition(M, 2, axis=1)

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])