---
title: "QR Decomposition of a Matrix"
description: "Using NumPy's qr function to compute the qr decomposition of a matrix."
tags: Numpy
URL: https://github.com/ageron/handson-ml
Licence: Apache License 2.0
Creator: 
Meta: ""

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	QR Decomposition of a Matrix
        </h1>
        <p>Using NumPy's qr function to compute the qr decomposition of a matrix.</p>
    	</div>
		</div> 

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Key Code
    	</span>
		</div>
		</div>
			

In [ ]:
import numpy as np
import numpy.linalg as linalg

The `qr` function computes the [QR decomposition](https://en.wikipedia.org/wiki/QR_decomposition) of a matrix:

In [ ]:
# orthogonal matrix q and upper triangular matrix r
q, r = linalg.qr(matrix)

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>
			

In [18]:
arr = np.array([[1,2,3],[5,7,11],[21,29,31]])
arr

array([[ 1,  2,  3],
       [ 5,  7, 11],
       [21, 29, 31]])

In [146]:
q, r = linalg.qr(arr)
q

array([[-0.04627448,  0.98786672,  0.14824986],
       [-0.23137241,  0.13377362, -0.96362411],
       [-0.97176411, -0.07889213,  0.22237479]])

In [147]:
r

array([[-21.61018278, -29.89331494, -32.80860727],
       [  0.        ,   0.62427688,   1.9894538 ],
       [  0.        ,   0.        ,  -3.26149699]])

In [148]:
q.dot(r)  # q.r equals arr

array([[  1.,   2.,   3.],
       [  5.,   7.,  11.],
       [ 21.,  29.,  31.]])