---
title: "Save and Load Array in Zipped Format"
description: "Save multiple arrays into one zipped file (.npz) and load them back into python."
tags: Numpy, Data Import / Connectivity / Injest
URL: https://github.com/ageron/handson-ml
Licence: Apache License 2.0
Creator: 
Meta: ""

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Save and Load Array in Zipped Format
        </h1>
        <p>Save multiple arrays into one zipped file (.npz) and load them back into python.</p>
    	</div>
		</div> 

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Key Code
    	</span>
		</div>
		</div>
			

In [ ]:
import numpy as np

## Saving

In [ ]:
# save arr1 2 and 3 into filename.npz
np.savez('filename', a = arr1, b = arr2, c = arr3)

## Loading

In [ ]:
# load data into dictionary-like object
my_arrays = np.load("filename.npz")
my_arrays["a"]   # => arr1
my_arrays.keys() # => a, b, c

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>
			

## Create arrays

In [169]:
a = np.random.rand(2,3)
a

array([[ 0.41307972,  0.20933385,  0.32025581],
       [ 0.19853514,  0.408001  ,  0.6038287 ]])

In [177]:
b = np.arange(24, dtype=np.uint8).reshape(2, 3, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=uint8)

## Save to 'my_zipped.npz'

In [178]:
np.savez("my_zipped", my_a=a, my_b=b)

## Let's take a peek at the file content
Note that the `.npz` file extension was automatically added.

In [179]:
with open("my_zipped.npz", "rb") as f:
    content = f.read()

repr(content)[:180] + "[...]"

u'"PK\\x03\\x04\\x14\\x00\\x00\\x00\\x00\\x00x\\x94cH\\xb6\\x96\\xe4{h\\x00\\x00\\x00h\\x00\\x00\\x00\\x08\\x00\\x00\\x00my_b.npy\\x93NUMPY\\x01\\x00F\\x00{\'descr\': \'|u1\', \'fortran_order\': False, \'shape\': (2,[...]'

## Load this file

In [180]:
my_arrays = np.load("my_zipped.npz")
my_arrays

## `my_arrays` is a dict-like object which loads the arrays lazily

In [181]:
my_arrays.keys()

['my_b', 'my_a']

In [182]:
my_arrays["my_a"]

array([[ 0.41307972,  0.20933385,  0.32025581],
       [ 0.19853514,  0.408001  ,  0.6038287 ]])