---
title: "Split Arrays"
description: "Splitting is the opposite of stacking arrays. We can use NumPy's split methods to split an array horizontally or vertically."
tags: Numpy
URL: https://github.com/ageron/handson-ml
Licence: Apache License 2.0
Creator: 
Meta: ""

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Split Arrays
        </h1>
        <p>Splitting is the opposite of stacking arrays. We can use NumPy's split methods to split an array horizontally or vertically.</p>
    	</div>
		</div> 

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Key Code
    	</span>
		</div>
		</div>
			

In [2]:
import numpy as np

In [ ]:
# split array vertically using
new_arr = np.vsplit(arr, num_of_divisions)
# or
new_arr = np.split(arr, num_of_divisions, axis = 0)

In [ ]:
# split array horizontally using
new_arr = np.hsplit(arr, num_of_divisions)
# or
new_arr = np.split(arr, num_of_divisions, axis = 1)

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>
			

## First let's create a 6x4 matrix:

In [119]:
r = np.arange(24).reshape(6,4)
r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## `vsplit`

In [120]:
r1, r2, r3 = np.vsplit(r, 3)
r1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [121]:
r2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [122]:
r3

array([[16, 17, 18, 19],
       [20, 21, 22, 23]])

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>
			

## `hsplit`

In [123]:
r4, r5 = np.hsplit(r, 2)
r4

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]])

In [124]:
r5

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])