---
title: "Transpose a Matrix"
description: "The T attribute for a NumPy matrix is equivalent to calling .transpose() when the rank is greater than or equal to 2."
tags: Numpy
URL: https://github.com/ageron/handson-ml
Licence: Apache License 2.0
Creator: 
Meta: ""

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Transpose a Matrix
        </h1>
        <p>The T attribute for a NumPy matrix is equivalent to calling .transpose() when the rank is greater than or equal to 2.</p>
    	</div>
		</div> 

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Key Code
    	</span>
		</div>
		</div>
			

In [ ]:
import numpy as np

The `T` attribute is equivalent to calling `transpose()` when the rank is ≥2. The `T` attribute has no effect on empty or rank 1 arrays.

In [ ]:
my_array = old_array.T

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>
			

In [132]:
m1 = np.arange(10).reshape(2,5)
m1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [133]:
m1.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>
			

## The `T` attribute has no effect on rank 0 (empty) or rank 1 arrays:

In [134]:
m2 = np.arange(5)
m2

array([0, 1, 2, 3, 4])

In [135]:
m2.T

array([0, 1, 2, 3, 4])

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>
			

## We can get the desired transposition by first reshaping the 1D array to a single-row matrix (2D):

In [136]:
m2r = m2.reshape(1,5)
m2r

array([[0, 1, 2, 3, 4]])

In [137]:
m2r.T

array([[0],
       [1],
       [2],
       [3],
       [4]])