---
title: "Conditional Operators For Arrays"
description: "Conditional operators apply element-wise in NumPy's ndarrays. "
tags: Python Fundamentals
URL: https://github.com/ageron/handson-ml
Licence: Apache License 2.0
Creator: 
Meta: ""

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Conditional Operators For Arrays
        </h1>
        <p>Conditional operators apply element-wise in NumPy's ndarrays. </p>
    	</div>
		</div> 

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Key Code
    	</span>
		</div>
		</div>
			

## The conditional operators also apply elementwise:

In [49]:
m = np.array([20, -5, 30, 40])
m < [15, 16, 35, 36]

array([False,  True,  True, False], dtype=bool)

## And using broadcasting:

In [50]:
m < 25  # equivalent to m < [25, 25, 25, 25]

array([ True,  True, False, False], dtype=bool)

## This is most useful in conjunction with boolean indexing:

In [51]:
m[m < 25]

array([20, -5])