---
title: "Create Arrays With A Range"
description: "Using NumPy's arange function which is similar to python's built-in range function to create arrays of a range of numbers."
tags: Python Fundamentals, Numpy
URL: https://github.com/ageron/handson-ml
Licence: Apache License 2.0
Creator: 
Meta: ""

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Create Arrays With A Range
        </h1>
        <p>Using NumPy's arange function which is similar to python's built-in range function to create arrays of a range of numbers.</p>
    	</div>
		</div> 

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Key Code
    	</span>
		</div>
		</div>
			

In [ ]:
# array of numbers from start up to but not including end
np.arange(start, end, step)

In [ ]:
# use linspace when working with floats
np.linspace(start, end, num_of_points)

The `linspace` function returns an array containing a specific number of points evenly distributed between two values (note that the maximum value is *included*, contrary to `arange`):

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>
			

In [15]:
np.arange(1, 5)

array([1, 2, 3, 4])

It also works with floats:

In [16]:
np.arange(1.0, 5.0)

array([ 1.,  2.,  3.,  4.])

Of course you can provide a step parameter:

In [17]:
np.arange(1, 5, 0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>
			

When dealing with floats, the exact number of elements in the array is not always predictible. <br> For example, consider this:

In [18]:
print(np.arange(0, 5/3, 1/3)) # depending on floating point errors, the max value is 4/3 or 5/3.
print(np.arange(0, 5/3, 0.333333333))
print(np.arange(0, 5/3, 0.333333334))

[ 0.          0.33333333  0.66666667  1.          1.33333333  1.66666667]
[ 0.          0.33333333  0.66666667  1.          1.33333333  1.66666667]
[ 0.          0.33333333  0.66666667  1.          1.33333334]


For this reason, it is generally preferable to use the `linspace` function instead of `arange` when working with floats.

In [19]:
print(np.linspace(0, 5/3, 6))

[ 0.          0.33333333  0.66666667  1.          1.33333333  1.66666667]
