---
title: "One-Dimensional Array Indexing"
description: "Indexing a one-dimensional numpy array is mostly like regular python arrays."
tags: Python Fundamentals
URL: https://github.com/ageron/handson-ml
Licence: Apache License 2.0
Creator: 
Meta: ""

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	One-Dimensional Array Indexing
        </h1>
        <p>Indexing a one-dimensional numpy array is mostly like regular python arrays.</p>
    	</div>
		</div> 

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Key Code
    	</span>
		</div>
		</div>
			

In [65]:
a = np.array([1, 5, 3, 19, 13, 7, 3])
a[3]

19

In [67]:
a[2:-1]

array([ 3, 19, 13,  7])

In [68]:
a[:2]

array([1, 5])

In [70]:
a[::-1]

array([ 3,  7, 13, 19,  3,  5,  1])

### You can modify elements:

In [71]:
a[3]=999
a

array([  1,   5,   3, 999,  13,   7,   3])

### You can also modify an `ndarray` slice:

In [72]:
a[2:5] = [997, 998, 999]
a

array([  1,   5, 997, 998, 999,   7,   3])

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Learn More
    	</span>
		</div>
		</div>
			

However, not all the features are the same. See the brick about the difference between indexing for numpy arrays and regular python arrays for more information.